# Generated by Django 2.1.7 on 2019-02-12 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kebun_binatang', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hewan',
            name='decription',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
