# Generated by Django 2.1.5 on 2019-02-13 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mentee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentee',
            name='model_pic',
            field=models.FileField(upload_to='../../Home/static/img/'),
        ),
    ]
