# Generated by Django 2.1.5 on 2019-02-11 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_mentee_nickname'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(max_length=50)),
                ('update', models.DateTimeField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('content', models.CharField(max_length=500)),
                ('created_by', models.CharField(max_length=50)),
            ],
        ),
    ]
