# Generated by Django 2.1.5 on 2019-02-13 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='Created',
        ),
        migrations.AddField(
            model_name='blog',
            name='model_pic',
            field=models.FileField(default=1, upload_to='static/img/'),
            preserve_default=False,
        ),
    ]
