# Generated by Django 2.1.5 on 2019-02-13 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('occupation', models.CharField(max_length=100)),
                ('quotes', models.TextField()),
                ('model_pic', models.FileField(upload_to='../../Home/static/img/')),
            ],
        ),
    ]
