# Generated by Django 2.1.5 on 2019-02-13 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mentor', '0002_auto_20190213_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='quotes',
            field=models.TextField(max_length=500),
        ),
    ]
