# Generated by Django 2.1.5 on 2019-02-11 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_challenge', models.CharField(max_length=100)),
                ('banyak_soal', models.CharField(max_length=10)),
                ('bobot_nilai', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Direksi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap', models.CharField(max_length=100)),
                ('no_telepon', models.CharField(max_length=10)),
                ('jabatan', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LiveCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_live_code', models.CharField(max_length=100)),
                ('banyak_soal', models.CharField(max_length=10)),
                ('bobot_nilai', models.CharField(max_length=10)),
                ('tanggal_pelaksanaan', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Mata_pelajaran',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_pelajaran', models.CharField(max_length=100)),
                ('jadwal_dimulai', models.DateTimeField()),
                ('jadwal_berakhir', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Mentee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap', models.CharField(max_length=100)),
                ('no_telepon', models.CharField(max_length=25)),
                ('nomor_absen', models.CharField(max_length=10)),
                ('nilai_rata_rata', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap', models.CharField(max_length=100)),
                ('no_telepon', models.CharField(max_length=10)),
                ('mata_pelajaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strukturATA.Mata_pelajaran')),
            ],
        ),
        migrations.AddField(
            model_name='livecode',
            name='mata_pelajaran',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strukturATA.Mata_pelajaran'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='mata_pelajaran',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strukturATA.Mata_pelajaran'),
        ),
    ]
