# Generated by Django 2.1.5 on 2019-02-11 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strukturATA', '0002_auto_20190211_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='no_telepon',
            field=models.CharField(max_length=25),
        ),
    ]
